"""
Django settings for lms project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool) #what's this? 
# its setting up the default value for the debug mode in the .env file 
# Everything in a .env file is a string. When Python reads DEBUG=True from the file, it gets the string "True" — not the boolean True.
# In Python, bool("False") is actually True (any non-empty string is truthy!). python-decouple's cast=bool handles this correctly — it converts the string "True" / "False" to proper Python booleans.

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost').split(',') #what's this? 
# its setting up the default value for the allowed hosts in the .env file 
# and splitting it into a list of strings 


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'loans',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# ─────────────────────────────────────────────────────────────
# Database Configuration
# USE_DOCKER=True  → PostgreSQL inside Docker (production-like)
# USE_DOCKER=False → SQLite on your local machine (fast dev)
#
# How to switch:
#   Local dev:  just run "python manage.py runserver" (USE_DOCKER defaults to False)
#   Docker:     docker compose sets USE_DOCKER=True via .env
# ─────────────────────────────────────────────────────────────

USE_DOCKER = config('USE_DOCKER', default=False, cast=bool)

if USE_DOCKER:
    # PostgreSQL — used when running inside Docker
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'lms_db',
            'USER': 'lms_user',
            'PASSWORD': 'lms_password',
            'HOST': config('DB_HOST', default='db'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
else:
    # SQLite — used for local development (no Docker needed)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Access Token expires (lasts 15 minutes).
# The frontend sends the Refresh Token to the /api/auth/token/refresh/ endpoint to get a new access token.
# Because ROTATE_REFRESH_TOKENS = True, the backend does two things:
# It sends back a new Access Token.
# It also sends back a brand new Refresh Token.
# Because BLACKLIST_AFTER_ROTATION = True, the old refresh token is added to a database blacklist table. If anyone tries to reuse that old refresh token, the server rejects it.


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (user uploads — profile pictures etc.)
MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.CustomUser'

# ─────────────────────────────────────────────────────────────
# PII Field Encryption & Hashing Keys
# WARNING: In production, load these from environment variables.
#          Never commit real keys to version control.
#
# Generate a valid Fernet key with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# ─────────────────────────────────────────────────────────────
FIELD_ENCRYPTION_KEY = config('FIELD_ENCRYPTION_KEY')
FIELD_HASH_KEY       = config('FIELD_HASH_KEY')
