# Generated by Django 6.0.6 on 2026-06-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_manager_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('LOAN_OFFICER', 'Loan_officer'), ('BORROWER', 'Borrower')], default='BORROWER', max_length=15),
        ),
    ]
