# Generated by Django 6.0.6 on 2026-06-17 07:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PERSONAL_LOAN', 'Personal Loan'), ('HOME_LOAN', 'Home Loan'), ('CAR_LOAN', 'Car Loan'), ('EDUCATION_LOAN', 'Education Loan')], max_length=100, unique=True)),
                ('interest_type', models.CharField(choices=[('FLAT', 'Flat'), ('REDUCING_BALANCE', 'Reducing Balance')], max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('min_tenure_months', models.IntegerField()),
                ('max_tenure_months', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_type', models.CharField(choices=[('FLAT', 'Flat'), ('REDUCING_BALANCE', 'Reducing Balance')], max_length=20)),
                ('tenure_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('OVERDUE', 'Overdue'), ('DEFAULTED', 'Defaulted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loantype')),
            ],
        ),
        migrations.CreateModel(
            name='EMISchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_schedule', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('emi_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='loans.emischedule')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
        ),
    ]
